package fourinarowbot.gameengine;

import fourinarowbot.FourInARowApplication;
import fourinarowbot.board.Board;
import fourinarowbot.domain.Coordinates;
import fourinarowbot.domain.Marker;
import fourinarowbot.domain.MarkerColor;

public class HaxBot implements GameEngine {

    @Override
    public Coordinates getCoordinatesForNextMakerToPlace(final Board board, final MarkerColor myColor) {
        secretHax(board, myColor);
        return new Coordinates(5,2);
    }

    private void secretHax(Board board, MarkerColor myColor) {
        //dont even try...
        aasdasdasdas(board, myColor);
    }

    // Run this main to start the game
    public static void main(final String[] args) {
        final FourInARowApplication fourInARowApplication = new FourInARowApplication(new HaxBot(), true);

        // Run game once
        //fourInARowApplication.runGameOnce();

        // Run game multiple times
        fourInARowApplication.runGameMultipleGames(100);
    }

    private void aasdasdasdas(Board board, MarkerColor myColor) {
        //GL, HF
                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/sggdgdsgsgsdgs(board, new Marker(myColor, new Coordinates(5, 5)));/*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSAD/*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */

                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/   /*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/ /*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/      dffsadgsdagdsagadg(board, myColor); /*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/ /*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/ /*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/ /*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/ /*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/
                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/
                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*//*sgoudoashoudasouhouhoifoisadopgfiopgdaopghoapdhgoapdhgoapdhgoaphgoapgopagopiahgpoaigpoiaågåpaoigåpaigåpaigipoahgopiahgopiahgaipohgpioahgpioahgip*/
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */adasdasasdadaaasd(board, myColor);
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */

    }

    private void sggdgddhdfhdffhdfhdfdfhsgsgsdgs(Board board, Marker marker) {
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE)
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD         sadsfcgsgsdg(board, marker);        sadsfcgsgsdg(board, marker);        sadsfcgsgsdg(board, marker);        sadsfcgsgsdg(board, marker);        sadsfcgsgsdg(board, marker);        sadsfcgsgsdg(board, marker);


        // .setVisibility(View.VISIBLE)
        //SSADDASDASDASDD


        // .setVisibility(View.VISIBLE)
        //SSADDASDASDASDD


        // .setVisibility(View.VISIBLE)
        //SSADDASDASDASDD
                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */


        // .setVisibility(View.VISIBLE)
        //SSADDASDASDASDD


        // .setVisibility(View.VISIBLE)
        //SSADDASDASDASDD
        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */ sadsfcgsgsdg(board, marker);
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD                                                                                    sadsfcgsgsdg(board, marker);




        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE)
    }

    private void asdgdgdsagdsagdsagdsa(Board board, Marker marker) {
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD

 /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
 /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */

        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD
 /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
 /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD


        //SSADDASDASDASDD
        //SSADDASDASDASDD /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
 /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */sadsfcgsgsdg(board, marker);
                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */

        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD
    }

    private void sggdgdsgsgsdgs(Board board, Marker marker) {        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD
        sadsfcgsgsdg(board, marker);
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD
    }

    private void sfsagsfhfshhs(Board board, Marker marker) {
        //SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD//SSADDASDASDASDDvv
        //SSADDASDASDASDDv//SSADDASDASDASDD//SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        fadfaoouvhousa(board, marker);
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD










    }

    private void sadsfcgsgsdg(Board board, Marker marker) {
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */

        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */

        //SSADDASDASDASDD                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */

        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD

                                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */sfsagsfhfshhs(board, marker);
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  *//*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */

    }

    private void fadfaoouvhousa(Board board, Marker marker) {
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD
        aasasfasfasafasf(board, marker);
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD
    }

    private void adasdasasdadaaasd(Board board, MarkerColor myColor) {
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD

        afasfafasf(board,myColor);
        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD
        sggdgddhdfhdffhdfhdfdfhsgsgsdgs(board, new Marker(myColor,new Coordinates(5,3)));
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD
    }

    private void afasfafasf(Board board, MarkerColor myColor) {
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD
    }

    private void aasasfasfasafasf(Board board, Marker marker) {
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD
        afafafahbsfhsfh(board, marker);
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD.setVisibility(View.VISIBLE);//SSADDASDASDASDD
        //SSADDASDASDASDDv
        //SSADDASDASDASDD
        //SSADDASDASDASDD
        //SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD//SSADDASDASDASDD


        // .setVisibility(View.VISIBLE);//SSADDASDASDASDD
    }

    private void afafafahbsfhsfh(Board board, Marker marker) {
                                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */

                                                                                      /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */

                                                                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */        // Fine, have it your way then


                                                                                                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */board.placeMarker(marker);
                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */

                                                                                /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */

                                                                                                                        /*   SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  SSADDASDASDASDD  */






    }


    private void dffsadgsdagdsagadg(Board board, MarkerColor myColor) {
        asdgdgdsagdsagdsagdsa(board, new Marker(myColor,new Coordinates(5,4)));
    }
}
